apiVersion: v2
name: onix-adapter
description: A Helm chart for Kubernetes

type: application

version: 1.0.0

appVersion: "latest" 

# Updated appVersion to reflect the latest Onix Adapter version
appVersion: "latest"

# Added maintainers section
#maintainers:
#  - name: YourName
#    email: your.email@example.com

